### PR TITLE
Fixed class error

### PR DESCRIPTION
**Pull request by Declan1704**
There was an error where in react for class we need to mention className. I fixed the error wherever it was occouring

### CODE REVIEW

**Comment by Ahsankhalid618** [comment]
@Declan1704 Your contributions are most welcome but raise an issue first, and if you got assigned, then raise a PR. and there is no need to change that class to className as it's font-awesome library preconfigured syntax.

**Comment by Declan1704** [comment]
The things is the background images what are there are not being displayed
when running. I tried to understand where's the issue but it's getting
difficult. Since there was an error occouring there, I thought of fixing it.

**Comment by Declan1704** [comment]
Actually none of the images are being displayed.

**Comment by Ahsankhalid618** [comment]
In react, images are pre-rendered, and className is just a syntax way of writing css classes in react, that is not the problem for images rendering. Maybe any other issue.

**Comment by Declan1704** [comment]
Yeah I know it... It's just that I thought of fixing it to see if anything
gets resolved. But the images aren't rendering...

**Pull request closed without merging**
