### PR TITLE
[feat] get device location weather details

### LINKED ISSUE #17: On load it will show weather of the user's current position
For now, when the web page loads it shows weather data of London, 
I will use Geolocation and ReverseGeolocation API to get the current city name such that the user will see weather of current locaiton of the user.

### PR DESCRIPTION
**Pull request by sujal1256**
Fixes #17 
The feature allows you to get location of your device location
It required the use of Geolocation API of Javascript and an external API from LocationIQ to get city name from latitude and longitude

https://github.com/user-attachments/assets/a73e73e4-aad0-4ca6-a2a9-19ea3d95f324

### CODE REVIEW

**Comment by Ahsankhalid618** [comment]
@sujal1256 Your changes are not working properly, is there something missing or did you change the API keys or what? explain the process in detail so I can get an idea,

The preview is loading for 10 mins but nothing working there.
image

**Comment by sujal1256** [comment]
Yes I did change the API keys, wait let me put them in the commit as well.
I think I forgot to make the commit

**Comment by sujal1256** [comment]
Please check once if it is still not showing up, because it is working on my machine properly

**Comment by Ahsankhalid618** [comment]
> Please check once if it is still not showing up, because it is working on my machine properly

Never push the API keys directly into code or commits, everything else is working fine, I have made some changes to your branch, check them, I changed it to REACT_APP_GEO_API & REACT_APP_API_KEY in both files, just do one thing, check it once more locally, add a .env file at the root and add the same API keys there which you added in your code now and then redeploy and if it works fine then tell me I'll merge it.

**Comment by sujal1256** [comment]
Yes It is working fine
Do you want me to commit a .env.example file?

**Comment by Ahsankhalid618** [comment]
> Yes It is working fine Do you want me to commit a .env.example file?

No, wait let me resolve the merge conflicts.

**Comment by sujal1256** [comment]
Ok sure

**Comment by sujal1256** [comment]
@Ahsankhalid618 Thank you for merging it, brother

**Pull request merged**
