### PR TITLE
Fix: Update default title and favicon

### LINKED ISSUE #7: [Bug]: Default Title 'React App' and Favicon Not Updated
### Description:
The website currently displays the default title "React App" in the browser tab and uses the default favicon. These should be customized to reflect the project's identity for better user experience and branding.
### Steps to Reproduce:
Open the website in a browser.
Notice the title displayed in the browser tab is "React App."
The favicon is also the default React icon.
### Expected Behavior:
The website title and favicon should be updated to match the project's name and branding.
### Actual Behavior:
The title remains "React App" and the favicon is the default React icon.
### Additional Context (optional):
Suggest specific titles or favicon designs if you have any recommendations.

### PR DESCRIPTION
**Pull request by muhammadashraf23**
### Summary
This pull request addresses the issue [#7](https://github.com/original-repository/issues/7), where the default title "React App" and the favicon were not updated. The changes made in this PR will set a more relevant title and update the favicon to match the project's branding.

### Changes Made
Updated the title in the public/index.html file from "React App" to "[Your Project's Name]" to better reflect the project's purpose.
Replaced the favicon in the public folder with a new favicon that represents the project's branding.
### Testing
Verified that the new title appears correctly in the browser tab.
Confirmed that the updated favicon is displayed in the browser.
### Related Issue
Closes #7

### CODE REVIEW

**Comment by muhammadashraf23** [comment]
@Ahsankhalid618 done

**Comment by Ahsankhalid618** [comment]
@MuhammadAshraf23 Can you add a snap/SS of the favicon here?

**Comment by muhammadashraf23** [comment]
> @MuhammadAshraf23 Can you add a snap/SS of the favicon here?

image

**Comment by Ahsankhalid618** [comment]
> > @MuhammadAshraf23 Can you add a snap/SS of the favicon here?
> 
> image

It's not an appropriate favicon for this app, Change it to something more suitable and please add the SS of the favicon on the App in chrome or whatever browser you are using.

**Comment by muhammadashraf23** [comment]
> > > @MuhammadAshraf23 Can you add a snap/SS of the favicon here?
> > 
> > 
> > image
> 
> It's not an appropriate favicon for this app, Change it to something more suitable and please add the SS of the favicon on the App in chrome or whatever browser you are using.

image

**Comment by muhammadashraf23** [comment]
This one is good?

**Comment by Ahsankhalid618** [comment]
> This one is good?

yeah, it looks good. implement it and then add the SS of the project with its favicon

**Comment by muhammadashraf23** [comment]
image

@Ahsankhalid618 Now check it

**Pull request merged**
