### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Amansingh0807**
In this update, we enhanced the README file for the Weather App by adding clear sections for contribution guidelines, features, future improvements and etc, along with acknowledgments to the open-source community and OpenWeatherMap for their support. 
I also created the Issue for it issue number #8 please look into it.

### CODE REVIEW

**Comment by Ahsankhalid618** [comment]
@Amansingh0807 Your contribution is most welcome but do remember, you can't directly raise a PR without an issue, either engage in an issue to get assigned and then raise a PR or create a new issue if you have something to contribute to the repo. That is the standard procedure to contribute in any open source repo.

**Now raise a new issue for update readme and I will assign you then mention the issue number in your PR above like #123 or whatever your issue number is.**

**Comment by Amansingh0807** [comment]
> Your contribution is most welcome but do remember, you can't directly raise a PR without an issue, either engage in an issue to get assigned and then raise a PR or create a new issue if you have something to contribute to the repo. That is the standard procedure to contribute in any open source repo.
> 
> **Now raise a new issue for update readme and I will assign you then mention the issue number in your PR above like #123 or whatever your issue number is.**

Thank you for your understanding! I apologize for forgetting to raise an issue before submitting my pull request; it was just a slip of my mind. I will make sure to follow the proper procedure in the future. I appreciate your guidance and will raise a new issue for the README update now. Thank you for assigning me!

**Comment by Ahsankhalid618** [comment]
> > Your contribution is most welcome but do remember, you can't directly raise a PR without an issue, either engage in an issue to get assigned and then raise a PR or create a new issue if you have something to contribute to the repo. That is the standard procedure to contribute in any open source repo.
> > **Now raise a new issue for update readme and I will assign you then mention the issue number in your PR above like #123 or whatever your issue number is.**
> 
> Thank you for your understanding! I apologize for forgetting to raise an issue before submitting my pull request; it was just a slip of my mind. I will make sure to follow the proper procedure in the future. I appreciate your guidance and will raise a new issue for the README update now. Thank you for assigning me!

No problem, we all make mistakes, of course that's how we learn.

**Comment by Ahsankhalid618** [comment]
#8 Resolved

**Pull request merged**
